title: "静能生慧" # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "学无止境"  # 一句话描述你的博客
baseurl: ""
url: "http://wsxq2.55555.io" # 此处填写你的博客地址 

owner: 
  name: "wsxq2" # 填写作者信息：名字
  email: "wsxq2@qq.com"# 填写作者信息：邮箱
  bio: "一只倔强的小强。" # 填写作者信息：博客描述

gavatar: /img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: /img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: wsxq2
facebook_username: 
weibo_username: 
zhihu_username: 

markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

timezone: Asia/Shanghai

defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "wsxq2" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  duoshuo :
    short_name :  # 填写你的 disqus id
  disqus :
      short_name :  # 填写你的 disqus id

google_analytics:  # 填写你  google_analytics id
google_verify:
bing_verify:
plugins: [jekyll-paginate]
