title: "静能生慧" # 你的博客名字，可以定义修订
header-img: "img/green.jpg"
tagline: "cn"  
description: "小强的博客，记录了踩各种坑的经历"  # 一句话描述你的博客
baseurl: ""
url: "https://wsxq2.55555.io" # 此处填写你的博客地址 

owner: 
  name: "wsxq2" # 填写作者信息：名字
  email: "wsxq2@qq.com" # 填写作者信息：邮箱
  bio: "小强的博客" # 填写作者信息：博客描述

gavatar: /img/favicon.png # 浏览器地址栏小图标，可自定义更改
favicon: /img/favicon.png # 浏览器地址栏小图标，可自定义更改

douban_username:  # 你的豆瓣id
twitter_username: 
github_username: wsxq2
facebook_username: 
weibo_username: 
zhihu_username: 

markdown: kramdown
# !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
# Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
#    # Rouge Options › https://github.com/jneen/rouge#full-options
    default_lang: plaintext
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

timezone: Asia/Shanghai

defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "wsxq2" # 你的名字
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white
      comments: true
      categories: "blog"

comments :
  provider : disqus # 使用 disqus 评论模块，读者翻墙才能看见
  disqus :
      short_name : wsxq2 # 填写你的 disqus id

google_analytics:  # 填写你  google_analytics id
google_verify:
bing_verify:
plugins:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap
    # - jekyll-last-modified-at
    # - jekyll-toc-generator

